# Generated by Django 5.0.6 on 2024-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002B86EED7560>', max_length=200),
        ),
    ]
