# Generated by Django 5.0.6 on 2024-12-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='pr0cd4990f', max_length=200),
        ),
    ]
