# Generated by Django 5.0.6 on 2025-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='pr89668781', max_length=200),
        ),
    ]
