# Generated by Django 5.0.6 on 2024-10-31 22:47

import core.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, choices=[(1, '🌟⭐⭐⭐⭐'), (2, '🌟🌟⭐⭐⭐'), (3, '🌟🌟🌟⭐⭐'), (4, '🌟🌟🌟🌟⭐'), (5, '🌟🌟🌟🌟🌟')], default=1, max_length=2, null=True)),
                ('agency_descript', models.TextField(default='Let the world know what is in your mind', max_length=300)),
                ('author_image', models.ImageField(default='./static/assets/images/1.jpg', upload_to=core.models.get_user_directory_path)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(default='+237692109697', max_length=25)),
                ('telegram', models.CharField(blank=True, max_length=25, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='Amazing writer', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('category_image', models.ImageField(default='./static/assets/images/1.jpg', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('profile_image', models.ImageField(default='./static/assets/images/2.jpg', upload_to='post')),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DB', 'DRAFT'), ('PB', 'Published')], default='DB', max_length=2)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.CharField(default='3 min', max_length=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Rating', models.IntegerField(blank=True, choices=[(1, '🌟⭐⭐⭐⭐'), (2, '🌟🌟⭐⭐⭐'), (3, '🌟🌟🌟⭐⭐'), (4, '🌟🌟🌟🌟⭐'), (5, '🌟🌟🌟🌟🌟')], default=1, null=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish', '-created'],
            },
        ),
    ]
