# Generated by Django 5.0.6 on 2024-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aid',
            field=models.UUIDField(default='aut83566c8', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.UUIDField(default='cat764a072', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.UUIDField(default='pos5018b33ea574', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
