# Generated by Django 5.0.6 on 2024-11-03 11:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='defaults/default.webp', upload_to=core.models.get_user_directory_path),
        ),
    ]
