# Generated by Django 5.0.6 on 2024-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_author_aid_alter_category_cid_alter_post_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='./static/assets/images/1.jpg', upload_to='category'),
        ),
    ]
