# Generated by Django 5.0.6 on 2024-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
    ]
