# Generated by Django 5.0.6 on 2024-09-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
