# Generated by Django 5.0.6 on 2024-09-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='./static/assets/images/2.jpg', upload_to='post'),
        ),
    ]
