# Generated by Django 5.0.6 on 2024-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='author', max_length=250),
        ),
    ]
