# Generated by Django 5.0.6 on 2024-09-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
    ]
