# Generated by Django 5.0.6 on 2024-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(default='Douala,Deido Rue 1372', max_length=350),
        ),
    ]
