# Generated by Django 5.0.6 on 2024-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.AddField(
            model_name='author',
            name='agency_descript',
            field=models.TextField(default="Whether you're here to discover inspiring articles or publish your own work, our agency is dedicated to helping you reach a broader audience and make a lasting impact."),
        ),
    ]
