# Generated by Django 5.0.6 on 2024-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DB', 'DRAFT'), ('PB', 'Published')], default='DB', max_length=2),
        ),
    ]
