# Generated by Django 5.0.6 on 2024-11-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_author_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='./static/assets/images/2.jpg', max_length=300, upload_to='post'),
        ),
    ]
