# Generated by Django 5.0.6 on 2024-12-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_post_alter_post_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
