# Generated by Django 5.0.6 on 2024-12-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_num',
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_view', to='core.post'),
        ),
    ]
