# Generated by Django 5.0.6 on 2024-10-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.AddField(
            model_name='author',
            name='agency_descript',
            field=models.TextField(default='Let the world know what is in your mind', max_length=300),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='Amazing writer', null=True),
        ),
    ]
