# Generated by Django 5.0.6 on 2024-11-03 11:12

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/default.webp', null=True, upload_to=userauth.models.get_user_directory_path),
        ),
    ]
