# Generated by Django 5.0.6 on 2024-09-06 17:40

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_customuser_bio_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to=userauth.models.get_user_directory_path),
        ),
    ]
